services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRESQL_LOG_STATEMENT: "all"
      POSTGRESQL_LOG_LINE_PREFIX: "%t [%p]: [%l-1] "
    command: >
      -c log_statement=all
      -c log_destination=stderr
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
